(() => {
  const nav=document.querySelector('.tabs'),app=document.querySelector('.app');
  if(!nav||!app)return;
  const oldPanel=document.getElementById('petGame'); if(oldPanel) oldPanel.remove();
  nav.querySelectorAll('[data-tab="petGame"]').forEach(x=>x.remove());

  const PETS=[
    {id:'otter',name:'小海獭',food:'小鱼干',body:'#9a6a45',belly:'#e9c8a1',accent:'#5a3d2c'},
    {id:'cat',name:'小猫',food:'猫罐头',body:'#e9a34f',belly:'#fff0cf',accent:'#8b5128'},
    {id:'dog',name:'小狗',food:'肉骨头',body:'#c79058',belly:'#f6d6aa',accent:'#70462d'},
    {id:'seal',name:'小海豹',food:'小鱼',body:'#aab8c8',belly:'#eef4f8',accent:'#64748b'},
    {id:'rabbit',name:'小兔',food:'胡萝卜',body:'#f2d7db',belly:'#fff7f4',accent:'#b67a85'},
    {id:'whale',name:'小鲸鱼',food:'海盐糖',body:'#6aa8d8',belly:'#dff4ff',accent:'#356b92'}
  ];
  const KEY='miyu_pet_v1',today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`},clamp=n=>Math.max(0,Math.min(100,n));
  const fresh=()=>({petId:'',name:'',food:0,hunger:70,mood:70,bond:0,lastDaily:'',streak:0,daily:{date:'',pet:0,play:0,talk:0}});
  let state=fresh(); try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}
  const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),info=()=>PETS.find(p=>p.id===state.petId)||PETS[0];

  const st=document.createElement('style');st.textContent=`
  .px-wrap{max-width:620px;margin:14px auto;font-family:"Courier New",monospace}.px-shell{background:#3d2b28;border:4px solid #2a1c1a;box-shadow:0 8px 0 #1f1514,0 14px 28px rgba(0,0,0,.18);border-radius:10px;overflow:hidden}.px-hud{display:flex;gap:8px;align-items:center;justify-content:space-between;flex-wrap:wrap;background:#6a4434;color:#fff7e6;padding:9px 10px;border-bottom:4px solid #2a1c1a;font-weight:900}.px-chip{background:#8b5e45;border:2px solid #2a1c1a;padding:5px 8px;box-shadow:inset 0 -2px 0 rgba(0,0,0,.18)}.px-room{position:relative;background:#c99a6d}.px-room canvas{display:block;width:100%;height:auto;image-rendering:pixelated;image-rendering:crisp-edges;touch-action:manipulation}.px-bubble{position:absolute;left:8%;right:8%;top:9%;background:#fff9ef;border:3px solid #553a31;box-shadow:4px 4px 0 rgba(42,28,26,.32);padding:8px 10px;text-align:center;font:900 13px/1.45 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;color:#4b322a}.px-actions{display:grid;grid-template-columns:repeat(4,1fr);gap:6px;padding:8px;background:#5d3c31;border-top:4px solid #2a1c1a}.px-btn{border:2px solid #2a1c1a;background:#f8e7c7;color:#3c2923;box-shadow:0 3px 0 #2a1c1a;padding:9px 4px;font-weight:950;font-size:12px}.px-btn:active{transform:translateY(2px);box-shadow:0 1px 0 #2a1c1a}.px-manage{display:flex;gap:7px;padding:8px;background:#4b332d;justify-content:center}.px-small{border:2px solid #261a18;background:#d9c1a7;padding:7px 10px;font-weight:900}.px-adopt{background:#f3dfbd;border:4px solid #3f2b25;padding:14px;box-shadow:0 7px 0 #2a1c1a}.px-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.px-choice{border:3px solid #6b4a39;background:#fff3d6;padding:10px 5px;text-align:center;font-weight:900;box-shadow:0 4px 0 #6b4a39}.px-choice.sel{background:#d9f0ff;border-color:#315f78}.px-icon{width:70px;height:60px;margin:0 auto 5px;image-rendering:pixelated}.px-name{width:100%;box-sizing:border-box;border:3px solid #5a4035;background:#fffdf5;padding:11px;font-size:16px;font-weight:900}.px-adoptgo{width:100%;margin-top:8px;border:3px solid #253e4d;background:#5da6cf;color:white;padding:11px;font-weight:950;box-shadow:0 4px 0 #253e4d}.px-note{font:700 11px/1.5 -apple-system,BlinkMacSystemFont,"PingFang SC",sans-serif;color:#6b5448;margin-top:8px;text-align:center}@media(max-width:620px){.px-wrap{margin:8px -2px}.px-actions{grid-template-columns:repeat(2,1fr)}.px-grid{grid-template-columns:repeat(2,1fr)}}`;
  document.head.appendChild(st);

  const btn=document.createElement('button');btn.className='tab-btn';btn.dataset.tab='petGame';btn.textContent='🐾 宠物';const calc=nav.querySelector('[data-tab="calculator"]'),data=nav.querySelector('[data-tab="data"]');if(calc)nav.insertBefore(btn,calc);else if(data)nav.insertBefore(btn,data);else nav.appendChild(btn);
  const panel=document.createElement('section');panel.id='petGame';panel.className='panel';panel.innerHTML='<div class="px-wrap"></div>';app.appendChild(panel);const root=panel.firstElementChild;
  const show=()=>{document.querySelectorAll('.tab-btn').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x===panel));const u=new URL(location.href);u.searchParams.set('streamer',new URLSearchParams(location.search).get('streamer')||'miyu');u.searchParams.set('tool','petGame');history.replaceState({},'',u)};btn.onclick=show;nav.addEventListener('click',e=>{const t=e.target.closest('.tab-btn');if(t&&t!==btn){btn.classList.remove('active');panel.classList.remove('active')}});

  function daily(){if(!state.petId)return false;const t=today();if(state.lastDaily===t)return false;const y=new Date();y.setDate(y.getDate()-1);const yy=`${y.getFullYear()}-${String(y.getMonth()+1).padStart(2,'0')}-${String(y.getDate()).padStart(2,'0')}`;state.streak=state.lastDaily===yy?(state.streak||0)+1:1;state.lastDaily=t;state.food=(state.food||0)+3;state.daily={date:t,pet:0,play:0,talk:0};state.hunger=clamp((state.hunger||70)-5);state.mood=clamp((state.mood||70)-3);save();return true}
  function counters(){if(!state.daily||state.daily.date!==today()){state.daily={date:today(),pet:0,play:0,talk:0};save()}}
  function esc(s){return String(s||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;')}

  function spriteCanvas(p,w=70,h=60){const c=document.createElement('canvas');c.width=w;c.height=h;c.className='px-icon';const x=c.getContext('2d');x.imageSmoothingEnabled=false;drawPet(x,p,w/2,h/2+8,1,false,0);return c}
  function renderAdopt(){let selected=state.petId||'otter';root.innerHTML='<div class="px-adopt"><div style="font-size:20px;font-weight:950">🐾 临海居宠物小屋</div><div class="px-note" style="text-align:left">选一只宠物，再给它取个名字。</div><div class="px-grid"></div><input id="pxName" class="px-name" maxlength="12" placeholder="宠物名字"><button id="pxGo" class="px-adoptgo">确认领养</button><div class="px-note">存档保存在当前浏览器；之后仍可改名。</div></div>';const g=root.querySelector('.px-grid');PETS.forEach(p=>{const b=document.createElement('button');b.className='px-choice'+(p.id===selected?' sel':'');b.type='button';b.dataset.id=p.id;b.appendChild(spriteCanvas(p));const d=document.createElement('div');d.textContent=p.name;b.appendChild(d);b.onclick=()=>{selected=p.id;g.querySelectorAll('.px-choice').forEach(q=>q.classList.toggle('sel',q===b))};g.appendChild(b)});root.querySelector('#pxGo').onclick=()=>{const p=PETS.find(v=>v.id===selected)||PETS[0],n=root.querySelector('#pxName').value.trim()||p.name;state={...fresh(),petId:p.id,name:n,food:3,hunger:78,mood:82,bond:5,lastDaily:today(),streak:1,daily:{date:today(),pet:0,play:0,talk:0}};save();renderRoom('欢迎回家！这里以后就是我的小窝啦。')};}

  let raf=0,walker=null;
  function renderRoom(msg=''){cancelAnimationFrame(raf);counters();const got=daily(),p=info();if(got&&!msg)msg=`今天签到成功，获得 ${p.food} ×3！`;root.innerHTML=`<div class="px-shell"><div class="px-hud"><span class="px-chip">🐾 ${esc(state.name||p.name)}</span><span class="px-chip">🍽️ ${state.food||0}</span><span class="px-chip">💗 ${state.bond||0}</span><span class="px-chip">🔥 ${state.streak||1}天</span></div><div class="px-room"><canvas id="pxRoom" width="320" height="430"></canvas><div class="px-bubble" id="pxBubble">${esc(msg||'我会自己在房间里逛逛，点我也可以互动喔。')}</div></div><div class="px-actions"><button class="px-btn" data-a="feed">🍖 喂食</button><button class="px-btn" data-a="pet">🤚 摸摸 ${state.daily.pet}/3</button><button class="px-btn" data-a="play">🎾 陪玩 ${state.daily.play}/3</button><button class="px-btn" data-a="talk">💬 说话 ${state.daily.talk}/5</button></div><div class="px-manage"><button class="px-small" data-a="rename">✏️ 改名</button><button class="px-small" data-a="reset">🔄 重新领养</button></div></div>`;root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>act(b.dataset.a));startRoom(p)}

  function startRoom(p){const c=root.querySelector('#pxRoom');if(!c)return;const x=c.getContext('2d');x.imageSmoothingEnabled=false;walker={x:158,y:315,tx:158,ty:315,face:1,wait:20,step:0,p};c.onclick=e=>{const r=c.getBoundingClientRect(),px=(e.clientX-r.left)*320/r.width,py=(e.clientY-r.top)*430/r.height;if(Math.hypot(px-walker.x,py-walker.y)<45){bubble('你点到我啦！');state.mood=clamp((state.mood||0)+1);save();walker.wait=35}};const loop=()=>{updateWalker();drawRoom(x);raf=requestAnimationFrame(loop)};loop()}
  function bubble(t){const b=root.querySelector('#pxBubble');if(b)b.textContent=t}
  function updateWalker(){if(!walker)return;if(walker.wait>0){walker.wait--;return}const dx=walker.tx-walker.x,dy=walker.ty-walker.y,d=Math.hypot(dx,dy);if(d<3){walker.wait=25+Math.floor(Math.random()*80);walker.tx=48+Math.random()*224;walker.ty=245+Math.random()*130;return}walker.face=dx<0?-1:1;walker.x+=dx/d*.7;walker.y+=dy/d*.55;walker.step+=.15}
  function drawRoom(g){g.clearRect(0,0,320,430);g.fillStyle='#f2e4ce';g.fillRect(0,0,320,145);for(let y=145;y<430;y+=24){for(let x=0;x<320;x+=40){g.fillStyle=((x/40+y/24)%2)?'#bd8d64':'#c99a6d';g.fillRect(x,y,40,24);g.fillStyle='#a77a58';g.fillRect(x,y,40,2)}}g.fillStyle='#8a5a43';g.fillRect(0,138,320,8);g.fillStyle='#8fc7d7';g.fillRect(30,32,92,68);g.fillStyle='#f7fbff';g.fillRect(36,38,80,56);g.fillStyle='#9ed0df';g.fillRect(74,38,4,56);g.fillRect(36,64,80,4);g.fillStyle='#fff5db';g.fillRect(210,32,70,54);g.fillStyle='#a66f4b';g.fillRect(206,28,78,8);g.fillRect(206,86,78,8);g.fillStyle='#866044';g.fillRect(34,184,72,44);g.fillStyle='#efd4a7';g.fillRect(40,190,60,32);g.fillStyle='#fff3d9';g.fillRect(55,198,30,18);g.fillStyle='#71513d';g.fillRect(205,194,64,18);g.fillStyle='#d9b07a';g.fillRect(212,212,50,42);g.fillStyle='#8b6248';g.fillRect(218,253,6,42);g.fillRect(250,253,6,42);g.fillStyle='#d7e8ce';g.fillRect(32,282,48,30);g.fillStyle='#7c9b71';g.fillRect(28,310,56,8);g.fillStyle='#f1d8a5';g.fillRect(116,334,88,34);g.fillStyle='#9a704d';g.fillRect(126,368,8,32);g.fillRect(186,368,8,32);g.fillStyle='#7eb27c';g.fillRect(270,145,8,55);g.fillStyle='#5f965f';g.fillRect(260,154,18,8);g.fillRect(270,166,18,8);g.fillRect(257,178,18,8);g.fillStyle='#77523b';g.fillRect(267,200,14,18);if(walker)drawPet(g,walker.p,walker.x,walker.y,1.45,walker.face<0,walker.step)}
  function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}
  function drawPet(g,p,cx,cy,s=1,flip=false,step=0){g.save();g.translate(cx,cy);g.scale(flip?-s:s,s);const bob=Math.sin(step)*1.5;g.translate(0,bob);const B=p.body,A=p.accent,V=p.belly;rect(g,-18,-18,36,28,B);rect(g,-14,8,28,16,B);rect(g,-10,10,20,13,V);rect(g,-14,-13,28,19,V);rect(g,-9,-8,5,5,'#fff');rect(g,4,-8,5,5,'#fff');rect(g,-7,-6,3,3,'#263238');rect(g,6,-6,3,3,'#263238');rect(g,-2,0,4,3,A);rect(g,-13,22,8,5,A);rect(g,5,22,8,5,A);if(p.id==='cat'){rect(g,-17,-25,9,10,B);rect(g,8,-25,9,10,B);rect(g,-15,-23,4,5,'#f4b5a7');rect(g,11,-23,4,5,'#f4b5a7');rect(g,14,10,15,5,B);rect(g,25,6,5,9,B)}else if(p.id==='dog'){rect(g,-18,-24,8,14,A);rect(g,10,-24,8,14,A);rect(g,14,12,14,5,B)}else if(p.id==='rabbit'){rect(g,-13,-38,8,20,B);rect(g,5,-38,8,20,B);rect(g,-10,-35,3,15,'#e8aeb7');rect(g,8,-35,3,15,'#e8aeb7')}else if(p.id==='seal'){rect(g,-20,14,8,8,B);rect(g,12,14,8,8,B);rect(g,14,9,12,5,B)}else if(p.id==='whale'){rect(g,-20,-6,40,22,B);rect(g,-26,-2,8,8,B);rect(g,18,-2,8,8,B);rect(g,12,14,10,6,B);rect(g,19,10,5,7,B)}else if(p.id==='otter'){rect(g,-16,-24,8,8,B);rect(g,8,-24,8,8,B);rect(g,14,12,15,5,B)}g.restore()}

  function act(a){const p=info();counters();if(a==='feed'){if((state.food||0)<1)return bubble('食物吃完啦，明天再来领吧～');if((state.hunger||0)>=100)return bubble('已经吃得饱饱的啦！');state.food--;state.hunger=clamp((state.hunger||0)+18);state.mood=clamp((state.mood||0)+3);state.bond=clamp((state.bond||0)+2);save();renderRoom(`好吃！${p.food}最好吃了！`)}else if(a==='pet'){if(state.daily.pet>=3)return bubble('今天已经被摸得很满足啦～');state.daily.pet++;state.mood=clamp(state.mood+8);state.bond=clamp(state.bond+3);save();renderRoom('嘿嘿，摸摸很舒服。')}else if(a==='play'){if(state.daily.play>=3)return bubble('今天玩累啦，明天再继续！');state.daily.play++;state.mood=clamp(state.mood+12);state.hunger=clamp(state.hunger-4);state.bond=clamp(state.bond+4);save();renderRoom('玩得超开心！我再跑一圈～')}else if(a==='talk'){if(state.daily.talk>=5)return bubble('今天聊很多啦，陪我安静待一会吧。');const lines=['今天也想听谜屿唱歌。','临海居今天很舒服～','你回来我就很开心。','等下还要陪我玩喔。','今天公屏会不会很热闹？'];state.daily.talk++;state.mood=clamp(state.mood+4);state.bond=clamp(state.bond+1);save();renderRoom(lines[(state.daily.talk-1)%lines.length])}else if(a==='rename'){const n=prompt('宠物的新名字：',state.name||p.name);if(n&&n.trim()){state.name=n.trim().slice(0,12);save();renderRoom('新名字我记住啦！')}}else if(a==='reset'){if(confirm('要重新选择宠物吗？目前亲密度与食物会重新开始。')){state=fresh();save();cancelAnimationFrame(raf);renderAdopt()}}}

  if(state.petId)renderRoom();else renderAdopt();
  if(new URLSearchParams(location.search).get('tool')==='petGame')show();
})();