(()=>{
const nav=document.querySelector('.tabs'),app=document.querySelector('.app');if(!nav||!app)return;
const KEY='miyu_pet_v1';
const PETS=[
{id:'otter',name:'小海獭',body:'#9b6b4a',belly:'#f1d2a8',accent:'#5a3c2b',cheek:'#e9a287'},
{id:'cat',name:'小猫',body:'#e6a257',belly:'#fff0cf',accent:'#85502e',cheek:'#f2a49d'},
{id:'dog',name:'小狗',body:'#c78e59',belly:'#f5d5aa',accent:'#6f472f',cheek:'#e9a287'},
{id:'crow',name:'小乌鸦',body:'#343943',belly:'#59616e',accent:'#1e2229',cheek:'#6f7784'},
{id:'rabbit',name:'小兔',body:'#efd6dc',belly:'#fff7f4',accent:'#ad7480',cheek:'#efa8ad'},
{id:'whale',name:'小鲸鱼',body:'#6ca8d6',belly:'#dff4ff',accent:'#356b92',cheek:'#96c9df'}];
const today=()=>new Date().toISOString().slice(0,10),fresh=()=>({petId:'',name:'',food:3,bond:5,merit:0,adoptedAt:today(),daily:{date:'',pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}});let state=fresh();try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{};if(state.petId==='seal')state.petId='crow';if(!state.adoptedAt)state.adoptedAt=state.lastDaily||today();const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),pet=()=>PETS.find(x=>x.id===state.petId)||PETS[0];
function ageDays(){const a=new Date(state.adoptedAt+'T00:00:00'),b=new Date(today()+'T00:00:00');return Math.max(1,Math.floor((b-a)/86400000)+1)}function stage(){const d=ageDays();return d<=3?{id:'baby',name:'幼儿期',scale:.86,head:2,body:-3,feature:-2}:d<=14?{id:'teen',name:'青少年期',scale:1,head:0,body:0,feature:1}:{id:'adult',name:'成年期',scale:1.1,head:-2,body:3,feature:4}}
function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function box(g,x,y,w,h,c,e='#6C5747'){rect(g,x-2,y-2,w+4,h+4,e);rect(g,x,y,w,h,c)}
function drawPet(g,p,cx,cy,s=1,flip=false,step=0,pose='idle',phase=0,st=stage()){g.save();g.translate(cx,cy+Math.sin(step)*1.1);g.scale((flip?-1:1)*s*st.scale,s*st.scale);const B=p.body,A=p.accent,V=p.belly,C=p.cheek,hy=-19+st.head,by=5;const bob=(pose==='eat'||pose==='pet'||pose==='play'||pose==='wood'||pose==='incense'||pose==='beads')?Math.sin(phase*6)*1.2:0;g.translate(0,bob);
box(g,-15,by,30,21+st.body,B,A);box(g,-18,hy,36,27,B,A);rect(g,-13,hy+7,26,16,V);rect(g,-10,hy+11,6,6,'#fff');rect(g,4,hy+11,6,6,'#fff');rect(g,-8,hy+13,3,3,'#263238');rect(g,6,hy+13,3,3,'#263238');if(st.id==='baby'){rect(g,-7,hy+12,2,2,'#fff');rect(g,7,hy+12,2,2,'#fff')}rect(g,-13,hy+18,5,3,C);rect(g,8,hy+18,5,3,C);rect(g,-2,hy+18,4,3,A);
const f=st.feature;if(p.id==='cat'){box(g,-17,hy-8-f,10,11+f,B,A);box(g,7,hy-8-f,10,11+f,B,A);rect(g,15,9,5+f,5,A)}else if(p.id==='dog'){box(g,-19,hy-7,9,15+f,A,A);box(g,10,hy-7,9,15+f,A,A);rect(g,14,10,5+f,4,A)}else if(p.id==='rabbit'){box(g,-13,hy-21-f,8,22+f,B,A);box(g,5,hy-21-f,8,22+f,B,A);rect(g,-10,hy-17-f,3,14+f,'#f3aeb9');rect(g,8,hy-17-f,3,14+f,'#f3aeb9');rect(g,15,12,5,5,B)}else if(p.id==='otter'){box(g,-17,hy-8,9,9,B,A);box(g,8,hy-8,9,9,B,A);rect(g,-13,10,7,8,V);rect(g,6,10,7,8,V)}else if(p.id==='crow'){box(g,-15,hy-7,8,7,B,A);box(g,7,hy-7,8,7,B,A);rect(g,16,hy+12,7+f,5,'#d9a441');rect(g,-19,6,7+f,15+f,A);rect(g,12,6,7+f,15+f,A);rect(g,-10,25+st.body,7,5+f,A);rect(g,3,25+st.body,7,5+f,A)}else if(p.id==='whale'){rect(g,15,4,8+f,5,B);rect(g,-20,8,7+f,5,B)}
rect(g,-12,27+st.body,8,5,A);rect(g,4,27+st.body,8,5,A);
if(pose==='eat'){
  box(g,-13,24,26,9,'#f4e4bf','#8a6d53');rect(g,-9,21,18,5,'#fff7dd');
  const chop=Math.sin(phase*12)*5;rect(g,7+chop,5,2,22,'#7a4b2b');rect(g,11+chop,4,2,23,'#9b6238');
  for(let i=0;i<7;i++){const a=phase*5+i*1.7,life=(phase*2+i*.17)%1;rect(g,8+Math.cos(a)*18*life,-2-Math.sin(a)*11*life,2,2,'#fff6d9')}
}
if(pose==='pet'){const y=hy-13+Math.abs(Math.sin(phase*5))*8;rect(g,-5,y,10,8,'#f3c6a5');rect(g,4,y+4,7,4,'#f3c6a5');for(let i=0;i<3;i++){const a=phase*3+i*2;rect(g,-18+i*17,hy-18-Math.abs(Math.sin(a))*10,4,4,'#f28fa6')}}
if(pose==='play'){const bx=Math.sin(phase*5)*22,by2=18-Math.abs(Math.cos(phase*5))*20;box(g,bx,by2,8,8,'#f2c14e','#5ea6e8');rect(g,-15,9+(Math.sin(phase*8)>0?0:4),7,5,B);rect(g,8,9+(Math.sin(phase*8)>0?4:0),7,5,B)}
if(pose==='wood'){const swing=-10+Math.sin(phase*4.8)*13;g.save();g.translate(12,3);g.rotate(swing*Math.PI/180);rect(g,0,-2,4,22,'#6B4631');box(g,-2,-8,8,7,'#B4845B','#6E4128');g.restore();}
if(pose==='incense'){rect(g,7,-9,2,18,'#B84A46');rect(g,11,-7,2,16,'#B84A46');const bow=Math.abs(Math.sin(phase*2.6))*5;g.translate(0,bow)}
if(pose==='beads'){for(let i=0;i<8;i++){const a=i/8*Math.PI*2+phase*3;rect(g,11+Math.cos(a)*7,5+Math.sin(a)*6,3,3,'#8A5A3A')}}g.restore()}
const css=document.createElement('style');css.textContent=`.px-wrap{max-width:620px;margin:8px auto;font-family:"Courier New",monospace}.px-shell{background:#E8DED0;border:4px solid #8D7867;box-shadow:0 8px 0 #C8B5A1;border-radius:12px;overflow:hidden}.px-hud{display:flex;gap:6px;justify-content:center;flex-wrap:wrap;background:#BFD6D2;padding:9px;border-bottom:4px solid #829C97}.px-chip{background:#E3EEEA;border:2px solid #829C97;padding:5px 7px;font-size:12px;font-weight:900}.px-room{position:relative}.px-room canvas{display:block;width:100%;image-rendering:pixelated}.px-bubble{position:absolute;left:12%;right:12%;top:4.5%;background:#FFFDF8;border:2px solid #B7A28E;padding:6px;text-align:center;font-weight:900}.px-actions,.px-rituals{display:grid;gap:7px;padding:8px}.px-actions{grid-template-columns:repeat(4,1fr);background:#D7E3DA}.px-rituals{grid-template-columns:repeat(3,1fr);background:#E9DFD1}.px-btn{border:2px solid #9B8A78;background:linear-gradient(#FFF7E3,#F2DEB9);box-shadow:0 3px 0 #B19D89;padding:10px 4px;font-weight:950}.px-btn:disabled{opacity:.45}.px-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.px-choice{border:3px solid #A38E7B;background:#FFF7E9;padding:8px;font-weight:900}.px-choice.sel{background:#DFF1F7}.px-icon{width:70px;height:64px;image-rendering:pixelated}.px-adopt{background:#F8EEDC;border:4px solid #9B8775;padding:14px}.px-name{width:100%;border:3px solid #A38E7B;padding:10px}.px-go{width:100%;margin-top:8px;padding:11px;background:#8FC5C4;border:3px solid #668D91;color:#fff;font-weight:950}@media(max-width:620px){.px-actions{grid-template-columns:repeat(2,1fr)}.px-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(css);document.getElementById('petGame')?.remove();nav.querySelectorAll('[data-tab="petGame"]').forEach(x=>x.remove());const tab=document.createElement('button');tab.className='tab-btn';tab.dataset.tab='petGame';tab.textContent='🐾 宠物';nav.appendChild(tab);const panel=document.createElement('section');panel.id='petGame';panel.className='panel active';panel.innerHTML='<div class="px-wrap"></div>';app.appendChild(panel);const root=panel.firstElementChild;
function preview(p){const c=document.createElement('canvas');c.width=70;c.height=64;c.className='px-icon';drawPet(c.getContext('2d'),p,35,42,1,false,0,'idle',0,{id:'baby',name:'幼儿期',scale:.86,head:2,body:-3,feature:-2});return c}function adopt(){let sel=state.petId||'otter';root.innerHTML='<div class="px-adopt"><b style="font-size:20px">🐾 选择你的宠物</b><div class="px-grid"></div><input class="px-name" maxlength="12" placeholder="宠物名字"><button class="px-go">确认领养</button></div>';const grid=root.querySelector('.px-grid');PETS.forEach(p=>{const b=document.createElement('button');b.className='px-choice'+(p.id===sel?' sel':'');b.append(preview(p),document.createElement('br'),p.name);b.onclick=()=>{sel=p.id;grid.querySelectorAll('.px-choice').forEach(x=>x.classList.toggle('sel',x===b))};grid.appendChild(b)});root.querySelector('.px-go').onclick=()=>{const p=PETS.find(x=>x.id===sel);state={...fresh(),petId:p.id,name:root.querySelector('.px-name').value.trim()||p.name,adoptedAt:today()};save();room('欢迎回家！')}}
let raf,busy=false,returnTimer=null,phase=0,w={x:160,y:318,tx:160,ty:318,face:1,step:0,pose:'idle'},TARGET={wood:{x:82,y:248,max:9999,merit:1},incense:{x:251,y:187,max:3,merit:5},beads:{x:250,y:299,max:5,merit:2},eat:{x:128,y:332},pet:{x:160,y:318},play:{x:188,y:330}};function counters(){if(!state.daily||state.daily.date!==today())state.daily={date:today(),pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}}function bubble(t){const b=document.getElementById('pxBubble');if(b)b.textContent=t}function buttons(on){root.querySelectorAll('.px-btn').forEach(b=>b.disabled=!on)}function cancelReturn(){if(returnTimer){clearTimeout(returnTimer);returnTimer=null}}function scheduleReturn(){cancelReturn();returnTimer=setTimeout(()=>{if(!busy){w.pose='idle';w.tx=160;w.ty=318;bubble('我回来啦～')}},5000)}
function drawRoom(g){g.clearRect(0,0,320,430);rect(g,0,0,320,145,'#F8F3EA');rect(g,0,145,320,285,'#D8C3A5');for(let y=145;y<430;y+=24)for(let x=0;x<320;x+=40)rect(g,x,y,40,2,'#C3A784');box(g,22,25,100,73,'#CDECF4');rect(g,70,27,4,69,'#fff8ee');rect(g,24,27,16,62,'#BFDAD7');rect(g,104,27,16,62,'#BFDAD7');box(g,219,177,65,11,'#846553');box(g,238,157,27,13,'#D6AF63');rect(g,246,134,3,24,'#B84A46');rect(g,254,136,3,22,'#B84A46');box(g,48,222,104,74,'#7E9A83');rect(g,55,229,90,60,'#D5E3D2');box(g,64,260,38,22,'#8E5736');box(g,113,345,48,17,'#9a7355');box(g,119,332,36,14,'#f0ddb9');for(let i=0;i<8;i++)box(g,242+(i%4)*8,286+Math.floor(i/4)*9,5,5,'#8A5A3A');drawPet(g,pet(),w.x,w.y,1.5,w.face<0,w.step,w.pose,phase,stage())}
function room(msg=''){cancelAnimationFrame(raf);counters();save();const st=stage();root.innerHTML=`<div class="px-shell"><div class="px-hud"><span class="px-chip">🐾 ${state.name||pet().name}</span><span class="px-chip">🌱 领养第 ${ageDays()} 天｜${st.name}</span><span class="px-chip">💗 ${state.bond||0}</span><span class="px-chip" id="merit">🙏 ${state.merit||0}</span></div><div class="px-room"><canvas id="pxRoom" width="320" height="430"></canvas><div class="px-bubble" id="pxBubble">${msg||'今天想做什么？'}</div></div><div class="px-rituals"><button class="px-btn" data-r="wood">🪵 敲木鱼</button><button class="px-btn" data-r="incense">🕯️ 上香</button><button class="px-btn" data-r="beads">📿 佛珠</button></div><div class="px-actions"><button class="px-btn" data-a="feed">🍚 吃饭</button><button class="px-btn" data-a="pet">🤚 摸摸</button><button class="px-btn" data-a="play">🎾 陪玩</button><button class="px-btn" data-a="talk">💬 说话</button></div></div>`;root.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>ritual(b.dataset.r));root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>act(b.dataset.a));const g=document.getElementById('pxRoom').getContext('2d');const loop=()=>{const dx=w.tx-w.x,dy=w.ty-w.y,d=Math.hypot(dx,dy);if(d>2){w.face=dx<0?-1:1;w.x+=dx/d*1.35;w.y+=dy/d*1.35;w.step+=.18}else w.step+=.035;phase+=.016;drawRoom(g);raf=requestAnimationFrame(loop)};loop()}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function walkTo(t,msg){cancelReturn();w.pose='idle';w.tx=t.x;w.ty=t.y;bubble(msg);while(Math.hypot(w.tx-w.x,w.ty-w.y)>5)await sleep(40)}
async function ritual(k){if(busy)return;counters();const t=TARGET[k];if((state.daily[k]||0)>=t.max)return bubble('今天这个修行已经完成啦～');busy=true;buttons(false);await walkTo(t,k==='wood'?'我去敲木鱼～':k==='incense'?'我去上香～':'我去拨佛珠～');w.pose=k;phase=0;if(k==='wood'){bubble('认真敲一下木鱼…');await sleep(2200)}else if(k==='incense'){bubble('合掌，拜一下…');await sleep(2600)}else{bubble('慢慢拨佛珠…');await sleep(3000)};state.daily[k]=(state.daily[k]||0)+1;state.merit=(state.merit||0)+t.merit;save();document.getElementById('merit').textContent='🙏 '+state.merit;bubble(k==='wood'?'功德 +1':k==='incense'?'上香完成，功德 +5':'佛珠完成，功德 +2');w.pose='idle';busy=false;buttons(true);scheduleReturn()}
async function act(a){if(busy)return;counters();cancelReturn();if(a==='talk'){state.bond+=1;save();bubble('我有在听～');scheduleReturn();return}busy=true;buttons(false);if(a==='feed'){if(state.food<1){busy=false;buttons(true);bubble('今天的饭吃完啦～');scheduleReturn();return}await walkTo(TARGET.eat,'开饭啦！');w.pose='eat';phase=0;bubble('拿筷子努力扒饭中… 🍚');await sleep(4700);state.food--;state.bond+=2;save();bubble('吃饱啦！饭粒都喷出来了 😋')}else if(a==='pet'){await walkTo(TARGET.pet,'来摸摸～');w.pose='pet';phase=0;bubble('摸摸摸摸摸～');await sleep(3200);state.bond+=3;save();bubble('嘿嘿，好舒服～')}else if(a==='play'){await walkTo(TARGET.play,'一起玩！');w.pose='play';phase=0;bubble('追球中！');await sleep(4200);state.bond+=4;save();bubble('玩得好开心！')}w.pose='idle';busy=false;buttons(true);scheduleReturn()}
if(state.petId){save();room()}else adopt();
})();