(()=>{
const nav=document.querySelector('.tabs'),app=document.querySelector('.app');if(!nav||!app)return;
const KEY='miyu_pet_v1',SK='miyu_pet_sound';
const PETS=[
{id:'otter',name:'小海獭',food:'小鱼干',body:'#9d6d4c',belly:'#f2d8b6',accent:'#60412f',cheek:'#eaa48c'},
{id:'cat',name:'小猫',food:'猫罐头',body:'#e7a35a',belly:'#fff0d0',accent:'#85502e',cheek:'#f2a49d'},
{id:'dog',name:'小狗',food:'肉骨头',body:'#c98f59',belly:'#f6d7ad',accent:'#70472f',cheek:'#eca48c'},
{id:'seal',name:'小海豹',food:'小鱼',body:'#aab9c9',belly:'#f1f6fa',accent:'#68798b',cheek:'#efb4ba'},
{id:'rabbit',name:'小兔',food:'胡萝卜',body:'#efd7de',belly:'#fff7f5',accent:'#ad7480',cheek:'#efa8ad'},
{id:'whale',name:'小鲸鱼',food:'海盐糖',body:'#6da9d7',belly:'#e1f5ff',accent:'#356b92',cheek:'#96c9df'}];
const fresh=()=>({petId:'',name:'',food:3,bond:5,merit:0,streak:1,lastDaily:'',daily:{date:'',pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}});
let state=fresh();try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{}
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));const pet=()=>PETS.find(x=>x.id===state.petId)||PETS[0];
function counters(){if(!state.daily||state.daily.date!==today())state.daily={date:today(),pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}}
let ac;function tone(f,d=.08,g=.04,type='sine',delay=0){if(localStorage.getItem(SK)==='0')return;try{ac??=new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),v=ac.createGain(),t=ac.currentTime+delay;o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.005);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(ac.destination);o.start(t);o.stop(t+d+.03)}catch{}}
function sfx(k){if(k==='wood'){tone(225,.04,.09,'triangle');tone(112,.14,.045,'sine',.01)}if(k==='incense'){tone(520,1.1,.04);tone(1040,.9,.02,'sine',.02)}if(k==='beads'){[0,.07,.14].forEach((d,i)=>tone(3500-i*250,.04,.022,'triangle',d))}}
const css=document.createElement('style');css.textContent=`.px-wrap{max-width:620px;margin:10px auto}.px-shell{overflow:hidden;border:3px solid #9b8069;border-radius:20px;background:#eadfce;box-shadow:0 10px 28px #5b463522}.px-hud{display:flex;gap:6px;justify-content:center;flex-wrap:wrap;padding:9px;background:#bfd5d0}.px-chip{padding:5px 8px;border:2px solid #829c97;border-radius:999px;background:#edf6f2;font:900 12px -apple-system,BlinkMacSystemFont,"PingFang SC"}.px-room{position:relative}.px-room canvas{display:block;width:100%;height:auto;touch-action:manipulation}.px-bubble{position:absolute;left:12%;right:12%;top:4%;padding:7px 10px;border:2px solid #b9a38f;border-radius:14px;background:#fffdf8;text-align:center;font:900 12px -apple-system,BlinkMacSystemFont,"PingFang SC";color:#62574e}.px-actions,.v9-rituals{display:grid;gap:7px;padding:8px}.px-actions{grid-template-columns:repeat(4,1fr);background:#dce8df}.v9-rituals{grid-template-columns:repeat(3,1fr);background:#efe3d2}.px-btn,.v9-rbtn{border:2px solid #a58c75;border-radius:14px;background:linear-gradient(#fff9ed,#f2dfbf);padding:10px 4px;font-weight:900;color:#59483c;box-shadow:0 3px 0 #c4aa8f}.v9-rbtn:disabled{opacity:.45}.px-manage{display:flex;gap:7px;justify-content:center;padding:8px;background:#eadfce}.px-small{border:2px solid #a58c75;border-radius:12px;background:#f7eddf;padding:7px 10px;font-weight:900}.px-adopt{background:#f8eedc;border:3px solid #9b8775;border-radius:18px;padding:14px}.px-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:9px;margin:12px 0}.px-choice{border:3px solid #a38e7b;border-radius:16px;background:#fff7e9;padding:8px 4px;font-weight:900}.px-choice.sel{background:#dff1f7;border-color:#72a2b2}.px-icon{width:78px;height:68px}.px-name{width:100%;padding:10px;border:3px solid #a38e7b;border-radius:12px}.px-adoptgo{width:100%;margin-top:8px;padding:11px;border:0;border-radius:12px;background:#78aaa9;color:#fff;font-weight:950}@media(max-width:620px){.px-actions{grid-template-columns:repeat(2,1fr)}.px-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(css);
const old=document.getElementById('petGame');if(old)old.remove();nav.querySelectorAll('[data-tab="petGame"]').forEach(x=>x.remove());
const btn=document.createElement('button');btn.className='tab-btn';btn.dataset.tab='petGame';btn.textContent='🐾 宠物';nav.appendChild(btn);const panel=document.createElement('section');panel.id='petGame';panel.className='panel active';panel.innerHTML='<div class="px-wrap"></div>';app.appendChild(panel);const root=panel.firstElementChild;
function ellipse(g,x,y,rx,ry,c,s='#614b3d',lw=2){g.beginPath();g.ellipse(x,y,rx,ry,0,0,Math.PI*2);g.fillStyle=c;g.fill();g.strokeStyle=s;g.lineWidth=lw;g.stroke()}
function path(g,pts,c,s='#614b3d',lw=2){g.beginPath();g.moveTo(pts[0][0],pts[0][1]);for(let i=1;i<pts.length;i++)g.lineTo(pts[i][0],pts[i][1]);g.closePath();g.fillStyle=c;g.fill();g.strokeStyle=s;g.lineWidth=lw;g.stroke()}
function face(g,p){ellipse(g,-7,-6,2.3,3,'#2f2c2a','#2f2c2a',1);ellipse(g,7,-6,2.3,3,'#2f2c2a','#2f2c2a',1);ellipse(g,0,1,8,6,p.belly,p.belly,1);ellipse(g,0,-1,2.4,1.8,p.accent,p.accent,1);g.strokeStyle=p.accent;g.lineWidth=1.5;g.beginPath();g.arc(-2,2,3,0,.8);g.stroke();g.beginPath();g.arc(2,2,3,2.34,3.14);g.stroke();ellipse(g,-11,1,3.5,2,p.cheek,p.cheek,1);ellipse(g,11,1,3.5,2,p.cheek,p.cheek,1)}
function drawPet(g,p,cx,cy,s=1,flip=false,step=0,pose='idle'){g.save();g.translate(cx,cy+Math.sin(step)*1.2);g.scale(flip?-s:s,s);const B=p.body,A=p.accent,V=p.belly;
if(p.id==='rabbit'){ellipse(g,0,7,15,18,B,A,2);ellipse(g,0,-12,17,16,B,A,2);ellipse(g,-8,-32,6,18,B,A,2);ellipse(g,8,-32,6,18,B,A,2);ellipse(g,-8,-31,2.5,12,'#f7b8c4','#f7b8c4',1);ellipse(g,8,-31,2.5,12,'#f7b8c4','#f7b8c4',1);ellipse(g,0,10,8,10,V,V,1);face(g,p);ellipse(g,14,13,5,6,B,A,2)}
else if(p.id==='cat'){ellipse(g,0,8,16,18,B,A,2);path(g,[[-17,-15],[-14,-31],[-4,-20]],B,A,2);path(g,[[17,-15],[14,-31],[4,-20]],B,A,2);ellipse(g,0,-11,18,16,B,A,2);ellipse(g,0,10,8,10,V,V,1);face(g,p);g.strokeStyle=A;g.lineWidth=3;g.beginPath();g.arc(17,9,12,-1.2,1.5);g.stroke();g.strokeStyle=A;g.lineWidth=1;[-4,0,4].forEach(y=>{g.beginPath();g.moveTo(-10,y);g.lineTo(-20,y-2);g.stroke();g.beginPath();g.moveTo(10,y);g.lineTo(20,y-2);g.stroke()})}
else if(p.id==='dog'){ellipse(g,0,8,17,19,B,A,2);ellipse(g,0,-11,18,16,B,A,2);ellipse(g,-17,-12,7,13,A,A,2);ellipse(g,17,-12,7,13,A,A,2);ellipse(g,0,10,8,11,V,V,1);face(g,p);g.strokeStyle=A;g.lineWidth=4;g.beginPath();g.arc(18,11,10,-.9,1.5);g.stroke()}
else if(p.id==='otter'){ellipse(g,0,8,17,20,B,A,2);ellipse(g,0,-11,18,16,B,A,2);ellipse(g,-13,-24,5,5,B,A,2);ellipse(g,13,-24,5,5,B,A,2);ellipse(g,0,9,10,12,V,V,1);face(g,p);ellipse(g,-11,12,5,8,B,A,2);ellipse(g,11,12,5,8,B,A,2)}
else if(p.id==='seal'){ellipse(g,0,8,21,16,B,A,2);ellipse(g,0,-10,18,15,B,A,2);face(g,p);ellipse(g,-20,12,8,5,B,A,2);ellipse(g,20,12,8,5,B,A,2);ellipse(g,0,9,10,8,V,V,1)}
else {ellipse(g,0,6,23,15,B,A,2);ellipse(g,-8,-8,17,14,B,A,2);ellipse(g,-4,5,11,8,V,V,1);face(g,p);path(g,[[19,3],[30,-4],[28,9]],B,A,2);ellipse(g,-19,7,6,4,B,A,2)}
if(pose==='wood'){g.strokeStyle='#6b4631';g.lineWidth=4;g.beginPath();g.moveTo(10,4);g.lineTo(24,-10);g.stroke();ellipse(g,25,-11,4,4,'#b4845b','#6b4631',2)}
if(pose==='incense'){g.strokeStyle='#b84a46';g.lineWidth=2;g.beginPath();g.moveTo(6,2);g.lineTo(6,-12);g.stroke();g.beginPath();g.moveTo(10,2);g.lineTo(10,-10);g.stroke()}
if(pose==='beads'){for(let i=0;i<7;i++){const a=i/7*Math.PI*2;ellipse(g,12+Math.cos(a)*6,5+Math.sin(a)*5,1.8,1.8,'#8a5a3a','#8a5a3a',1)}}g.restore()}
function preview(p){const c=document.createElement('canvas');c.width=78;c.height=68;c.className='px-icon';drawPet(c.getContext('2d'),p,39,46,.95,false,0);return c}
function adopt(){let sel=state.petId||'rabbit';root.innerHTML='<div class="px-adopt"><b style="font-size:20px">🐾 临海居宠物小屋</b><div class="px-grid"></div><input class="px-name" maxlength="12" placeholder="宠物名字"><button class="px-adoptgo">确认领养</button></div>';const grid=root.querySelector('.px-grid');PETS.forEach(p=>{const b=document.createElement('button');b.className='px-choice'+(p.id===sel?' sel':'');b.appendChild(preview(p));b.append(document.createElement('br'),p.name);b.onclick=()=>{sel=p.id;grid.querySelectorAll('.px-choice').forEach(x=>x.classList.toggle('sel',x===b))};grid.appendChild(b)});root.querySelector('.px-adoptgo').onclick=()=>{const p=PETS.find(x=>x.id===sel);state={...fresh(),petId:sel,name:root.querySelector('.px-name').value.trim()||p.name,lastDaily:today(),daily:{date:today(),pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}};save();room('欢迎回家！')}}
let raf,busy=false,w={x:160,y:318,tx:160,ty:318,face:1,step:0,wait:20,pose:'idle'};
const TARGET={wood:{x:82,y:248,max:9999,merit:1},incense:{x:251,y:187,max:3,merit:5},beads:{x:250,y:299,max:5,merit:2}};
function bubble(t){const b=document.getElementById('pxBubble');if(b)b.textContent=t}
function room(msg=''){cancelAnimationFrame(raf);counters();root.innerHTML=`<div class="px-shell"><div class="px-hud"><span class="px-chip">🐾 ${state.name||pet().name}</span><span class="px-chip">💗 ${state.bond||0}</span><span class="px-chip" id="meritChip">🙏 ${state.merit||0}</span></div><div class="px-room"><canvas id="pxRoom" width="320" height="430"></canvas><div class="px-bubble" id="pxBubble">${msg||'今天想做什么？'}</div></div><div class="v9-rituals"><button class="v9-rbtn" data-r="wood">🪵 敲木鱼</button><button class="v9-rbtn" data-r="incense">🕯️ 上香</button><button class="v9-rbtn" data-r="beads">📿 佛珠</button></div><div class="px-actions"><button class="px-btn" data-a="feed">🍖 喂食</button><button class="px-btn" data-a="pet">🤚 摸摸</button><button class="px-btn" data-a="play">🎾 陪玩</button><button class="px-btn" data-a="talk">💬 说话</button></div><div class="px-manage"><button class="px-small" data-a="reset">🔄 重新领养</button></div></div>`;root.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>ritual(b.dataset.r));root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>act(b.dataset.a));const c=document.getElementById('pxRoom'),g=c.getContext('2d');const loop=()=>{update();draw(g);raf=requestAnimationFrame(loop)};loop()}
function draw(g){g.clearRect(0,0,320,430);g.fillStyle='#f7f1e8';g.fillRect(0,0,320,145);g.fillStyle='#d8c3a5';g.fillRect(0,145,320,285);for(let y=145;y<430;y+=28){g.strokeStyle='#c3a784';g.beginPath();g.moveTo(0,y);g.lineTo(320,y);g.stroke()}g.fillStyle='#cfeaf1';g.fillRect(25,28,98,66);g.strokeStyle='#7a6656';g.lineWidth=5;g.strokeRect(25,28,98,66);g.fillStyle='#846553';g.fillRect(220,176,66,12);g.fillRect(228,188,7,38);g.fillRect(271,188,7,38);g.fillStyle='#d6af63';g.fillRect(239,158,28,14);g.fillStyle='#b84a46';g.fillRect(248,137,3,21);g.fillRect(255,139,3,19);g.fillStyle='#d5e3d2';g.fillRect(48,220,104,76);ellipse(g,83,272,24,14,'#8e5736','#6e4128',3);g.strokeStyle='#6b4631';g.lineWidth=5;g.beginPath();g.moveTo(104,246);g.lineTo(134,226);g.stroke();for(let i=0;i<10;i++){const a=i/10*Math.PI*2;ellipse(g,250+Math.cos(a)*18,292+Math.sin(a)*14,3,3,'#8a5a3a','#8a5a3a',1)}g.fillStyle='#f0ddb6';g.fillRect(130,350,78,32);drawPet(g,pet(),w.x,w.y,1.55,w.face<0,w.step,w.pose)}
function update(){if(busy){w.step+=.12;return}if(w.wait-->0){w.step+=.04;return}const dx=w.tx-w.x,dy=w.ty-w.y,d=Math.hypot(dx,dy);if(d<3){w.wait=45+Math.random()*80;w.tx=55+Math.random()*210;w.ty=260+Math.random()*105;return}w.face=dx<0?-1:1;w.x+=dx/d*.75;w.y+=dy/d*.58;w.step+=.18}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function ritual(k){if(busy)return;const t=TARGET[k];counters();if((state.daily[k]||0)>=t.max){bubble(k==='incense'?'今天已经上过三次香啦～':'今天佛珠已经摸够五次啦～');return}busy=true;document.querySelectorAll('.v9-rbtn').forEach(b=>b.disabled=true);const ox=w.x,oy=w.y;w.tx=t.x;w.ty=t.y;while(Math.hypot(w.x-t.x,w.y-t.y)>5){const dx=t.x-w.x,dy=t.y-w.y,d=Math.hypot(dx,dy);w.face=dx<0?-1:1;w.x+=dx/d*2.2;w.y+=dy/d*1.8;w.step+=.3;await sleep(16)}w.pose=k;bubble(k==='wood'?'认真敲一下木鱼～':k==='incense'?'去上香啦～':'拨一拨佛珠～');await sleep(220);sfx(k);await sleep(k==='incense'?850:500);state.daily[k]=(state.daily[k]||0)+1;state.merit=(Number(state.merit)||0)+t.merit;save();document.getElementById('meritChip').textContent='🙏 '+state.merit;bubble(`功德 +${t.merit}`);w.pose='idle';while(Math.hypot(w.x-ox,w.y-oy)>5){const dx=ox-w.x,dy=oy-w.y,d=Math.hypot(dx,dy);w.face=dx<0?-1:1;w.x+=dx/d*2.2;w.y+=dy/d*1.8;w.step+=.3;await sleep(16)}busy=false;document.querySelectorAll('.v9-rbtn').forEach(b=>b.disabled=false)}
function act(a){if(a==='reset'){if(confirm('要重新选择宠物吗？')){state=fresh();save();cancelAnimationFrame(raf);adopt()}return}if(a==='feed'){state.bond=(state.bond||0)+2;bubble('好吃！')}if(a==='pet'){state.bond=(state.bond||0)+2;bubble('摸摸很舒服～')}if(a==='play'){state.bond=(state.bond||0)+3;bubble('玩得好开心！')}if(a==='talk')bubble('今天也想陪你听歌。');save()}
btn.onclick=()=>{panel.classList.add('active')};if(state.petId)room();else adopt();
})();
