(()=>{
const SK='miyu_pet_sound';localStorage.setItem(SK,'0');let c;
const ac=()=>{try{c??=new(window.AudioContext||window.webkitAudioContext)();if(c.state==='suspended')c.resume();return c}catch{return null}};
function tone(f,d,g,type='sine',delay=0){const x=ac();if(!x)return;const o=x.createOscillator(),v=x.createGain(),t=x.currentTime+delay;o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.004);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(x.destination);o.start(t);o.stop(t+d+.04)}
function noise(d=.04,g=.03,f=1800,q=1.2,delay=0){const x=ac();if(!x)return;const n=Math.max(1,Math.floor(x.sampleRate*d)),buf=x.createBuffer(1,n,x.sampleRate),a=buf.getChannelData(0);for(let i=0;i<n;i++)a[i]=(Math.random()*2-1)*Math.pow(1-i/n,2.4);const s=x.createBufferSource(),bp=x.createBiquadFilter(),v=x.createGain(),t=x.currentTime+delay;s.buffer=buf;bp.type='bandpass';bp.frequency.value=f;bp.Q.value=q;v.gain.setValueAtTime(g,t);v.gain.exponentialRampToValueAtTime(.0001,t+d);s.connect(bp);bp.connect(v);v.connect(x.destination);s.start(t)}
function wood(){noise(.025,.055,900,.8);tone(182,.16,.075,'sine');tone(286,.105,.045,'triangle',.006);tone(92,.19,.035,'sine',.01)}
function bell(){noise(.025,.012,4200,1.8);[[530,2.25,.07],[1012,1.8,.04],[1572,1.35,.028],[2088,.9,.014]].forEach(([f,d,g],i)=>tone(f,d,g,'sine',i*.006))}
function beads(){for(let i=0;i<3;i++){const d=i*.05;noise(.028,.026-i*.004,4200+i*180,1.8,d);tone(4300-i*170,.045,.014,'triangle',d)}}
let last='';function hook(){const b=document.getElementById('pxBubble');if(!b||b.dataset.audioHook)return false;b.dataset.audioHook='1';new MutationObserver(()=>{const t=b.textContent||'';if(t===last)return;last=t;if(t.includes('功德 +1'))wood();else if(t.includes('上香完成'))bell();else if(t.includes('佛珠完成'))beads()}).observe(b,{childList:true,subtree:true,characterData:true});return true}
new MutationObserver(()=>hook()).observe(document.body,{childList:true,subtree:true});hook();
})();