(()=>{
const nav=document.querySelector('.tabs'),app=document.querySelector('.app');if(!nav||!app)return;
const KEY='miyu_pet_v1',SK='miyu_pet_sound';
const PETS=[
{id:'otter',name:'小海獭',food:'小鱼干',body:'#9b6b4a',belly:'#f1d2a8',accent:'#5a3c2b',cheek:'#e9a287'},
{id:'cat',name:'小猫',food:'猫罐头',body:'#e6a257',belly:'#fff0cf',accent:'#85502e',cheek:'#f2a49d'},
{id:'dog',name:'小狗',food:'肉骨头',body:'#c78e59',belly:'#f5d5aa',accent:'#6f472f',cheek:'#e9a287'},
{id:'crow',name:'小乌鸦',food:'亮晶晶果',body:'#343943',belly:'#59616e',accent:'#1e2229',cheek:'#6f7784'},
{id:'rabbit',name:'小兔',food:'胡萝卜',body:'#efd6dc',belly:'#fff7f4',accent:'#ad7480',cheek:'#efa8ad'},
{id:'whale',name:'小鲸鱼',food:'海盐糖',body:'#6ca8d6',belly:'#dff4ff',accent:'#356b92',cheek:'#96c9df'}];
const today=()=>new Date().toISOString().slice(0,10),fresh=()=>({petId:'',name:'',food:3,bond:5,merit:0,adoptedAt:today(),daily:{date:'',pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}});let state=fresh();try{state=Object.assign(fresh(),JSON.parse(localStorage.getItem(KEY)||'{}'))}catch{};if(state.petId==='seal')state.petId='crow';if(!state.adoptedAt)state.adoptedAt=state.lastDaily||today();const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),pet=()=>PETS.find(x=>x.id===state.petId)||PETS[0];
function ageDays(){const a=new Date(state.adoptedAt+'T00:00:00'),b=new Date(today()+'T00:00:00');return Math.max(1,Math.floor((b-a)/86400000)+1)}function stage(){const d=ageDays();return d<=3?{id:'baby',name:'幼儿期',scale:.86,head:2,body:-3,feature:-2}:d<=14?{id:'teen',name:'青少年期',scale:1,head:0,body:0,feature:1}:{id:'adult',name:'成年期',scale:1.1,head:-2,body:3,feature:4}}
function rect(g,x,y,w,h,c){g.fillStyle=c;g.fillRect(Math.round(x),Math.round(y),Math.round(w),Math.round(h))}function box(g,x,y,w,h,c,e='#6C5747'){rect(g,x-2,y-2,w+4,h+4,e);rect(g,x,y,w,h,c)}
function drawPet(g,p,cx,cy,s=1,flip=false,step=0,pose='idle',st=stage()){g.save();g.translate(cx,cy+Math.sin(step)*1.1);g.scale((flip?-1:1)*s*st.scale,s*st.scale);const B=p.body,A=p.accent,V=p.belly,C=p.cheek,hy=-19+st.head,by=5;
// cardboard body proportions visibly mature
box(g,-15,by,30,21+st.body,B,A);box(g,-18,hy,36,27,B,A);rect(g,-13,hy+7,26,16,V);rect(g,-10,hy+11,6,6,'#fff');rect(g,4,hy+11,6,6,'#fff');rect(g,-8,hy+13,3,3,'#263238');rect(g,6,hy+13,3,3,'#263238');if(st.id==='baby'){rect(g,-7,hy+12,2,2,'#fff');rect(g,7,hy+12,2,2,'#fff')}rect(g,-13,hy+18,5,3,C);rect(g,8,hy+18,5,3,C);rect(g,-2,hy+18,4,3,A);
const f=st.feature;if(p.id==='cat'){box(g,-17,hy-8-f,10,11+f,B,A);box(g,7,hy-8-f,10,11+f,B,A);rect(g,15,9,5+f,5,A);if(st.id==='adult'){rect(g,-3,hy+3,6,3,'#c77b38');rect(g,-15,hy+4,5,3,'#c77b38')}}
else if(p.id==='dog'){box(g,-19,hy-7,9,15+f,A,A);box(g,10,hy-7,9,15+f,A,A);rect(g,14,10,5+f,4,A)}
else if(p.id==='rabbit'){box(g,-13,hy-21-f,8,22+f,B,A);box(g,5,hy-21-f,8,22+f,B,A);rect(g,-10,hy-17-f,3,14+f,'#f3aeb9');rect(g,8,hy-17-f,3,14+f,'#f3aeb9');rect(g,15,12,5,5,B)}
else if(p.id==='otter'){box(g,-17,hy-8,9,9,B,A);box(g,8,hy-8,9,9,B,A);rect(g,-13,10,7,8,V);rect(g,6,10,7,8,V);if(st.id==='adult')rect(g,15,12,8,4,A)}
else if(p.id==='crow'){box(g,-15,hy-7,8,7,B,A);box(g,7,hy-7,8,7,B,A);rect(g,16,hy+12,7+f,5,'#d9a441');rect(g,-19,6,7+f,15+f,A);rect(g,12,6,7+f,15+f,A);rect(g,-10,25+st.body,7,5+f,A);rect(g,3,25+st.body,7,5+f,A);if(st.id==='adult'){rect(g,-14,hy+3,8,3,'#5966a0');rect(g,6,hy+3,8,3,'#5966a0')}}
else if(p.id==='whale'){rect(g,15,4,8+f,5,B);rect(g,-20,8,7+f,5,B);if(st.id==='adult')rect(g,-13,hy+3,26,3,'#8ac4e8')}
if(st.id==='baby'){rect(g,-11,27+st.body,8,4,A);rect(g,3,27+st.body,8,4,A)}else{rect(g,-12,27+st.body,8,5,A);rect(g,4,27+st.body,8,5,A)}
if(pose==='wood'){rect(g,12,-1,4,18,'#6B4631');box(g,11,-7,8,7,'#B4845B','#6E4128')}if(pose==='incense'){rect(g,8,-8,2,17,'#B84A46');rect(g,12,-6,2,15,'#B84A46')}if(pose==='beads'){for(let i=0;i<6;i++)rect(g,11+(i%3)*4,2+Math.floor(i/3)*4,3,3,'#8A5A3A')}g.restore()}
let ac;function tone(f,d=.08,g=.04,type='sine',delay=0){if(localStorage.getItem(SK)==='0')return;try{ac??=new(window.AudioContext||window.webkitAudioContext)();ac.resume();const o=ac.createOscillator(),v=ac.createGain(),t=ac.currentTime+delay;o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.005);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(ac.destination);o.start(t);o.stop(t+d+.03)}catch{}}function sfx(k){if(k==='wood'){tone(250,.045,.08,'triangle');tone(125,.13,.04,'sine',.01)}if(k==='incense'){tone(523,1.2,.04);tone(1046,.9,.02,'sine',.02)}if(k==='beads')[0,.07,.14].forEach((d,i)=>tone(3400-i*220,.04,.02,'triangle',d))}
const css=document.createElement('style');css.textContent=`.px-wrap{max-width:620px;margin:8px auto;font-family:"Courier New",monospace}.px-shell{background:#E8DED0;border:4px solid #8D7867;box-shadow:0 8px 0 #C8B5A1;border-radius:12px;overflow:hidden}.px-hud{display:flex;gap:6px;justify-content:center;flex-wrap:wrap;background:#BFD6D2;padding:9px;border-bottom:4px solid #829C97}.px-chip{background:#E3EEEA;border:2px solid #829C97;padding:5px 7px;font-size:12px;font-weight:900}.px-room{position:relative}.px-room canvas{display:block;width:100%;image-rendering:pixelated}.px-bubble{position:absolute;left:12%;right:12%;top:4.5%;background:#FFFDF8;border:2px solid #B7A28E;padding:6px;text-align:center;font-weight:900}.px-actions,.px-rituals{display:grid;gap:7px;padding:8px}.px-actions{grid-template-columns:repeat(4,1fr);background:#D7E3DA}.px-rituals{grid-template-columns:repeat(3,1fr);background:#E9DFD1}.px-btn{border:2px solid #9B8A78;background:linear-gradient(#FFF7E3,#F2DEB9);box-shadow:0 3px 0 #B19D89;padding:10px 4px;font-weight:950}.px-btn:disabled{opacity:.45}.px-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.px-choice{border:3px solid #A38E7B;background:#FFF7E9;padding:8px;font-weight:900}.px-choice.sel{background:#DFF1F7}.px-icon{width:70px;height:64px;image-rendering:pixelated}.px-adopt{background:#F8EEDC;border:4px solid #9B8775;padding:14px}.px-name{width:100%;border:3px solid #A38E7B;padding:10px}.px-go{width:100%;margin-top:8px;padding:11px;background:#8FC5C4;border:3px solid #668D91;color:#fff;font-weight:950}@media(max-width:620px){.px-actions{grid-template-columns:repeat(2,1fr)}.px-grid{grid-template-columns:repeat(2,1fr)}}`;document.head.appendChild(css);document.getElementById('petGame')?.remove();nav.querySelectorAll('[data-tab="petGame"]').forEach(x=>x.remove());const btn=document.createElement('button');btn.className='tab-btn';btn.dataset.tab='petGame';btn.textContent='🐾 宠物';nav.appendChild(btn);const panel=document.createElement('section');panel.id='petGame';panel.className='panel active';panel.innerHTML='<div class="px-wrap"></div>';app.appendChild(panel);const root=panel.firstElementChild;
function preview(p){const c=document.createElement('canvas');c.width=70;c.height=64;c.className='px-icon';drawPet(c.getContext('2d'),p,35,42,1,false,0,'idle',{id:'baby',name:'幼儿期',scale:.86,head:2,body:-3,feature:-2});return c}function adopt(){let sel=state.petId||'otter';root.innerHTML='<div class="px-adopt"><b style="font-size:20px">🐾 选择你的宠物</b><div class="px-grid"></div><input class="px-name" maxlength="12" placeholder="宠物名字"><button class="px-go">确认领养</button></div>';const grid=root.querySelector('.px-grid');PETS.forEach(p=>{const b=document.createElement('button');b.className='px-choice'+(p.id===sel?' sel':'');b.append(preview(p),document.createElement('br'),p.name);b.onclick=()=>{sel=p.id;grid.querySelectorAll('.px-choice').forEach(x=>x.classList.toggle('sel',x===b))};grid.appendChild(b)});root.querySelector('.px-go').onclick=()=>{const p=PETS.find(x=>x.id===sel);state={...fresh(),petId:p.id,name:root.querySelector('.px-name').value.trim()||p.name,adoptedAt:today()};save();room('欢迎回家！')}}
let raf,busy=false,w={x:160,y:318,tx:160,ty:318,face:1,step:0,pose:'idle'},TARGET={wood:{x:82,y:248,max:9999,merit:1},incense:{x:251,y:187,max:3,merit:5},beads:{x:250,y:299,max:5,merit:2}};function counters(){if(!state.daily||state.daily.date!==today())state.daily={date:today(),pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0}}function bubble(t){const b=document.getElementById('pxBubble');if(b)b.textContent=t}
function drawRoom(g){g.clearRect(0,0,320,430);rect(g,0,0,320,145,'#F8F3EA');rect(g,0,145,320,285,'#D8C3A5');for(let y=145;y<430;y+=24)for(let x=0;x<320;x+=40){rect(g,x,y,40,2,'#C3A784')}box(g,22,25,100,73,'#CDECF4');rect(g,70,27,4,69,'#fff8ee');rect(g,24,27,16,62,'#BFDAD7');rect(g,104,27,16,62,'#BFDAD7');box(g,219,177,65,11,'#846553');box(g,238,157,27,13,'#D6AF63');rect(g,246,134,3,24,'#B84A46');rect(g,254,136,3,22,'#B84A46');box(g,48,222,104,74,'#7E9A83');rect(g,55,229,90,60,'#D5E3D2');box(g,64,260,38,22,'#8E5736');box(g,130,349,75,31,'#F0DDB6');for(let i=0;i<8;i++)box(g,242+(i%4)*8,286+Math.floor(i/4)*9,5,5,'#8A5A3A');drawPet(g,pet(),w.x,w.y,1.5,w.face<0,w.step,w.pose,stage())}
function room(msg=''){cancelAnimationFrame(raf);counters();save();const st=stage();root.innerHTML=`<div class="px-shell"><div class="px-hud"><span class="px-chip">🐾 ${state.name||pet().name}</span><span class="px-chip">🌱 领养第 ${ageDays()} 天｜${st.name}</span><span class="px-chip">💗 ${state.bond||0}</span><span class="px-chip" id="merit">🙏 ${state.merit||0}</span></div><div class="px-room"><canvas id="pxRoom" width="320" height="430"></canvas><div class="px-bubble" id="pxBubble">${msg||'今天想做什么？'}</div></div><div class="px-rituals"><button class="px-btn" data-r="wood">🪵 敲木鱼</button><button class="px-btn" data-r="incense">🕯️ 上香</button><button class="px-btn" data-r="beads">📿 佛珠</button></div><div class="px-actions"><button class="px-btn" data-a="feed">🍖 喂食</button><button class="px-btn" data-a="pet">🤚 摸摸</button><button class="px-btn" data-a="play">🎾 陪玩</button><button class="px-btn" data-a="talk">💬 说话</button></div></div>`;root.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>ritual(b.dataset.r));root.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>act(b.dataset.a));const g=document.getElementById('pxRoom').getContext('2d');const loop=()=>{const dx=w.tx-w.x,dy=w.ty-w.y,d=Math.hypot(dx,dy);if(d>2){w.face=dx<0?-1:1;w.x+=dx/d*1.35;w.y+=dy/d*1.35;w.step+=.18}else w.step+=.035;drawRoom(g);raf=requestAnimationFrame(loop)};loop()}
const sleep=ms=>new Promise(r=>setTimeout(r,ms));async function ritual(k){if(busy)return;counters();const t=TARGET[k];if((state.daily[k]||0)>=t.max)return bubble('今天这个修行已经完成啦～');busy=true;root.querySelectorAll('.px-btn').forEach(b=>b.disabled=true);w.tx=t.x;w.ty=t.y;bubble('🐾 我过去啦～');while(Math.hypot(w.tx-w.x,w.ty-w.y)>5)await sleep(50);w.pose=k;await sleep(300);sfx(k);await sleep(k==='incense'?700:380);state.daily[k]=(state.daily[k]||0)+1;state.merit=(state.merit||0)+t.merit;save();document.getElementById('merit').textContent='🙏 '+state.merit;bubble((k==='wood'?'功德 +1':k==='incense'?'上香完成，功德 +5':'佛珠完成，功德 +2'));w.pose='idle';w.tx=160;w.ty=318;busy=false;root.querySelectorAll('.px-btn').forEach(b=>b.disabled=false)}function act(a){if(a==='feed'){if(state.food<1)return bubble('食物吃完啦～');state.food--;state.bond+=2}else if(a==='pet')state.bond+=3;else if(a==='play')state.bond+=4;else if(a==='talk')state.bond+=1;save();bubble(a==='feed'?'好吃！':a==='pet'?'摸摸很舒服～':a==='play'?'一起玩！':'我有在听～')}
if(state.petId){save();room()}else adopt();
})();