(()=>{
const KEY='miyu_pet_v1',SK='miyu_pet_sound';let busy=false,ctx;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const audio=()=>{try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();return ctx}catch{return null}};
function tone(f,d=.08,g=.05,type='sine',delay=0){if(localStorage.getItem(SK)==='0')return;const c=audio();if(!c)return;const o=c.createOscillator(),v=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.006);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(c.destination);o.start(t);o.stop(t+d+.03)}
function sfx(k){if(k==='wood'){tone(235,.045,.085,'triangle');tone(118,.13,.04,'sine',.012)}if(k==='incense'){tone(523,1.4,.045);tone(1046,1.05,.022,'sine',.015);tone(1568,.8,.012,'sine',.025)}if(k==='beads'){[0,.07,.14].forEach((d,i)=>tone(3400-i*260,.045,.025,'triangle',d))}}
const css=document.createElement('style');css.textContent=`.v8-rituals{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:8px;background:#efe3d2;border-top:2px solid #c8b29a}.v8-rbtn{border:2px solid #a88c70;border-radius:14px;background:linear-gradient(#fffaf0,#f2dfbf);padding:10px 4px;font-weight:900;color:#59483c;box-shadow:0 3px 0 #c5aa8e}.v8-rbtn:disabled{opacity:.45}`;document.head.appendChild(css);
function bubble(t){const b=document.getElementById('pxBubble');if(b){b.textContent=t;b.style.opacity=1}}
const targets={wood:{x:82,y:248,label:'🪵 敲木鱼',max:9999,merit:1},incense:{x:251,y:187,label:'🕯️ 上香',max:3,merit:5},beads:{x:250,y:299,label:'📿 佛珠',max:5,merit:2}};
function roomCanvas(){return document.querySelector('#petGame #pxRoom')}
function dispatchAt(t){const c=roomCanvas();if(!c)return;const r=c.getBoundingClientRect();c.dispatchEvent(new PointerEvent('pointerdown',{bubbles:true,clientX:r.left+t.x/320*r.width,clientY:r.top+t.y/430*r.height,pointerId:1,pointerType:'touch',isPrimary:true}));c.dispatchEvent(new PointerEvent('pointerup',{bubbles:true,clientX:r.left+t.x/320*r.width,clientY:r.top+t.y/430*r.height,pointerId:1,pointerType:'touch',isPrimary:true}));}
async function perform(k){if(busy)return;const t=targets[k];let s=read();s.daily&&s.daily.date===today()||(s.daily={date:today(),pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0});if((s.daily[k]||0)>=t.max){bubble(k==='incense'?'今天已经上过三次香啦～':'今天佛珠已经摸够五次啦～');return}busy=true;document.querySelectorAll('.v8-rbtn').forEach(b=>b.disabled=true);bubble('🐾 我去'+(k==='wood'?'敲木鱼':k==='incense'?'上香':'拨佛珠')+'啦～');dispatchAt(t);await sleep(850);sfx(k);await sleep(k==='incense'?900:520);s=read();bubble(`${t.label}完成`);busy=false;document.querySelectorAll('.v8-rbtn').forEach(b=>b.disabled=false)}
function mount(){document.querySelectorAll('.v8-actor').forEach(x=>x.remove());const shell=document.querySelector('#petGame .px-shell');if(!shell||shell.querySelector('.v8-rituals'))return false;const bar=document.createElement('div');bar.className='v8-rituals';['wood','incense','beads'].forEach(k=>{const b=document.createElement('button');b.className='v8-rbtn';b.textContent=targets[k].label;b.onclick=()=>perform(k);bar.appendChild(b)});const actions=shell.querySelector('.px-actions');shell.insertBefore(bar,actions||null);return true}
let n=0;const timer=setInterval(()=>{if(mount()||++n>50)clearInterval(timer)},100);
})();
