(()=>{
const KEY='miyu_pet_v1',SK='miyu_pet_sound';let busy=false,ctx;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
const save=s=>localStorage.setItem(KEY,JSON.stringify(s));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const audio=()=>{try{ctx??=new(window.AudioContext||window.webkitAudioContext)();ctx.resume();return ctx}catch{return null}};
function tone(f,d=.08,g=.05,type='sine',delay=0){if(localStorage.getItem(SK)==='0')return;const c=audio();if(!c)return;const o=c.createOscillator(),v=c.createGain(),t=c.currentTime+delay;o.type=type;o.frequency.value=f;v.gain.setValueAtTime(.0001,t);v.gain.exponentialRampToValueAtTime(g,t+.006);v.gain.exponentialRampToValueAtTime(.0001,t+d);o.connect(v);v.connect(c.destination);o.start(t);o.stop(t+d+.03)}
function sfx(k){if(k==='wood'){tone(235,.045,.085,'triangle');tone(118,.13,.04,'sine',.012)}if(k==='incense'){tone(523,1.4,.045);tone(1046,1.05,.022,'sine',.015);tone(1568,.8,.012,'sine',.025)}if(k==='beads'){[0,.07,.14].forEach((d,i)=>tone(3400-i*260,.045,.025,'triangle',d))}}
const css=document.createElement('style');css.textContent=`.v8-rituals{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:8px;background:#efe3d2;border-top:2px solid #c8b29a}.v8-rbtn{border:2px solid #a88c70;border-radius:14px;background:linear-gradient(#fffaf0,#f2dfbf);padding:10px 4px;font-weight:900;color:#59483c;box-shadow:0 3px 0 #c5aa8e}.v8-rbtn:disabled{opacity:.45}.v8-actor{position:absolute;z-index:7;left:50%;top:69%;width:48px;height:48px;transform:translate(-50%,-50%);transition:left .72s cubic-bezier(.2,.8,.2,1),top .72s cubic-bezier(.2,.8,.2,1);pointer-events:none;filter:drop-shadow(0 3px 2px #6b4d3833)}.v8-face{position:absolute;inset:5px 4px 2px;border:3px solid #6d4c38;border-radius:48% 48% 43% 43%;background:#e8a55d}.v8-ear{position:absolute;top:0;width:15px;height:16px;background:#e8a55d;border:3px solid #6d4c38;transform:rotate(45deg);z-index:-1}.v8-ear.a{left:5px}.v8-ear.b{right:5px}.v8-eye{position:absolute;top:20px;width:4px;height:5px;background:#4a3429;border-radius:50%}.v8-eye.a{left:15px}.v8-eye.b{right:15px}.v8-muzzle{position:absolute;left:15px;top:27px;width:18px;height:11px;background:#fff1d6;border-radius:50%}.v8-nose{position:absolute;left:22px;top:28px;width:5px;height:4px;background:#49342a;border-radius:50%}.v8-actor.walk{animation:v8bob .18s infinite alternate}.v8-actor.perform{animation:v8do .18s 4 alternate}.v8-actor.wood:after{content:'🔨';position:absolute;right:-13px;top:9px;font-size:19px;transform-origin:bottom left;animation:v8hit .22s 3}.v8-actor.incense:after{content:'🙏';position:absolute;right:-15px;top:17px;font-size:18px}.v8-actor.beads:after{content:'📿';position:absolute;right:-16px;top:14px;font-size:19px}@keyframes v8bob{to{transform:translate(-50%,-54%) rotate(2deg)}}@keyframes v8do{to{transform:translate(-50%,-54%) scale(1.04)}}@keyframes v8hit{50%{transform:rotate(-38deg)}}`;
document.head.appendChild(css);
function bubble(t){const b=document.getElementById('pxBubble');if(b){b.textContent=t;b.style.opacity=1}}
function actor(){let a=document.querySelector('.v8-actor');if(a)return a;const room=document.querySelector('#petGame .px-room');if(!room)return null;a=document.createElement('div');a.className='v8-actor';a.innerHTML='<i class="v8-ear a"></i><i class="v8-ear b"></i><i class="v8-face"></i><i class="v8-eye a"></i><i class="v8-eye b"></i><i class="v8-muzzle"></i><i class="v8-nose"></i>';room.appendChild(a);return a}
const targets={wood:{left:'25%',top:'61%',label:'🪵 敲木鱼',max:9999,merit:1},incense:{left:'78%',top:'45%',label:'🕯️ 上香',max:3,merit:5},beads:{left:'78%',top:'70%',label:'📿 佛珠',max:5,merit:2}};
async function perform(k){if(busy)return;const a=actor(),t=targets[k];if(!a)return;let s=read();s.daily&&s.daily.date===today()||(s.daily={date:today(),pet:0,play:0,talk:0,incense:0,beads:0,pray:0,wood:0});if((s.daily[k]||0)>=t.max){bubble(k==='incense'?'今天已经上过三次香啦～':'今天佛珠已经摸够五次啦～');return}busy=true;document.querySelectorAll('.v8-rbtn').forEach(b=>b.disabled=true);bubble('🐾 我去'+(k==='wood'?'敲木鱼':k==='incense'?'上香':'拨佛珠')+'啦～');a.className='v8-actor walk';a.style.left=t.left;a.style.top=t.top;await sleep(760);a.className='v8-actor perform '+k;await sleep(180);sfx(k);await sleep(k==='incense'?900:520);s.daily[k]=(s.daily[k]||0)+1;s.merit=(Number(s.merit)||0)+t.merit;save(s);const m=document.getElementById('meritChip');if(m)m.textContent='🙏 '+s.merit;bubble(`${t.label}完成｜功德 +${t.merit}`);a.className='v8-actor walk';a.style.left='50%';a.style.top='69%';await sleep(760);a.className='v8-actor';busy=false;document.querySelectorAll('.v8-rbtn').forEach(b=>b.disabled=false)}
function mount(){const shell=document.querySelector('#petGame .px-shell');if(!shell||shell.querySelector('.v8-rituals'))return false;const bar=document.createElement('div');bar.className='v8-rituals';['wood','incense','beads'].forEach(k=>{const b=document.createElement('button');b.className='v8-rbtn';b.textContent=targets[k].label;b.onclick=()=>perform(k);bar.appendChild(b)});const actions=shell.querySelector('.px-actions');shell.insertBefore(bar,actions||null);actor();return true}
let n=0;const timer=setInterval(()=>{if(mount()||++n>50)clearInterval(timer)},100);
})();